schema: ./schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://graphql.datocms.com
      headers:
        authorization: ${DATOCMS_TOKEN}
        user-agent: JS GraphQL
      introspect: false
